{
 "title": "Dashboard Cliente 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "sucrusal", "label": "Sucrusal", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 19, "x": 2, "y": 0 },
   "options": {
    "content": "<img src=\"https://drive.google.com/uc?export=view&id=1TZUfG0xX_Yj-BJLr8r9wJ2VQvJTDtIyf\" />"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Estados de fallas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Reportes",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Falla de reporte",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Reportes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "units": "none",
     "valueDisplayRegex": "50",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "ANDE",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Falla ANDE",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EstadoANDE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "bottom"
       }
      ]
     ],
     "units": "none",
     "valueDisplayRegex": "50",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "Falla Gral.",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Falla Gral",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EstadoFalla",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "bottom"
       }
      ]
     ],
     "units": "none",
     "valueDisplayRegex": "50",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "Bateria",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Desconectada",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "descBat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "bottom"
       }
      ]
     ],
     "units": "none",
     "valueDisplayRegex": "50",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "Generador",
   "type": "vonage-status-panel",
   "description": "en reposo",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Activo",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EstadoGen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "bottom"
       }
      ]
     ],
     "units": "none",
     "valueDisplayRegex": "100",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "Fuga Combustible",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Falla Gral",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FugaGas",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "bottom"
       }
      ]
     ],
     "units": "none",
     "valueDisplayRegex": "50",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  { "title": "Variables electricas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Tension R",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tension S",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tension T",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Carga R",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Carga S",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Carga T",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Datos Generales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Horas de trabajo",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "horas" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "horaTrabajada",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura de motor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Tmotor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Combustible",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NivelCombustible",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bateria",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NivelBateria",
     "query": "SELECT last(\"value\") FROM \"NivelBateria\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bateria Mod. Telemetria",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batGSM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Historiales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Historial de bateria",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NivelBateria",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historial de combustible",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NivelCombustible",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historial de Tension ANDE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historial de Carga",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}